### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mwien** [mwien/einwortspiel#2]
#### UI:
- [x]  change button to black font on white background
- [x] change topbar (https://fly.io/phoenix-files/make-your-liveview-feel-faster/)
- [x] add copy url button (https://fly.io/phoenix-files/copy-to-clipboard-with-phoenix-liveview/)
- [x] make things consistent (e.g. rounding of buttons same etc)

#### Content:
- [x] add rules and stuff to home
- [x] #3
- [x] add Impressum

#### Logic:
- [x] if game cannot be found, redirect to home

#### Other:
- [x] add SSL support
